In [1]:
from torch import tensor
import torch

In [2]:
'''
predict sum of three numbers plus one
'''

'\npredict sum of three numbers plus one\n'

In [129]:
x = torch.randint(-100,100,(100000,10)).float().to('cuda')
w1=torch.rand(10,10).to('cuda')-1
b1=torch.rand(10).to('cuda')-1
w2=torch.rand(10,1).to('cuda')-1
b2=torch.rand(1).to('cuda')-1

y=x.sum(1) + 1
lr=0.000001

In [139]:
for i in range(1000000):
    idxs=torch.randint(0,x.shape[0],(1000,))
    mb=x[idxs]
    mby=y[idxs]
    
    
    z1=mb@w1 + b1
    z1=z1.squeeze()
    a1 = z1.clone()
    
    z2 = a1 @ w2 + b2
    z2 = z2.squeeze()
    a2 = z2.relu()
    
    loss = (a2-mby).pow(2).mean()
    if i == 21000:
        None#import pdb; pdb.set_trace()
    
    # layer 2
    dlda=2*(a2-mby) / mb.shape[0]
    dadz=(z2>0).float()
    dldz=(dlda) * dadz # same length of batch size
    
    dldw = a1.t() @ dldz[:,None]
    dldb=(dldz).sum()
    dldz.shape,dldw.shape,dldb
    
    dldz.shape,w2.shape
    
    # layer 1 
    dlda1 = dldz[:,None] @ w2.t()
    
    da1dz1=(z1 > 0).float()
    dldz1=dlda1 * da1dz1
    
    
    dldw1=mb.t() @ dldz1
    dldb1 = dldz1.sum(0)

    w2 -= lr * dldw
    b2 -= lr * dldb
    w1 -= lr * dldw1
    b1 -= lr * dldb1
    
    if i%10000 == 0:
        print('---',i,loss)#,w2.grad[:10], dldw[:10],w1.grad[:10],dldw1[:10])

z1=x@w1 + b1
z1=z1.squeeze()

z2 = z1 @ w2 + b2
z2 = z2.squeeze()
acc = (z2.round().int() == y.int()).float().mean()
mae = (z2-y).abs().mean()
z2[:10].round().int(),y[:10].int(),'acc',acc,'mae',mae

--- 0 tensor(0.0004, device='cuda:0')
--- 10000 tensor(0.0004, device='cuda:0')
--- 20000 tensor(0.0004, device='cuda:0')
--- 30000 tensor(0.0003, device='cuda:0')
--- 40000 tensor(0.0003, device='cuda:0')
--- 50000 tensor(0.0003, device='cuda:0')
--- 60000 tensor(0.0003, device='cuda:0')
--- 70000 tensor(0.0002, device='cuda:0')
--- 80000 tensor(0.0002, device='cuda:0')
--- 90000 tensor(0.0002, device='cuda:0')
--- 100000 tensor(0.0002, device='cuda:0')
--- 110000 tensor(0.0002, device='cuda:0')
--- 120000 tensor(0.0002, device='cuda:0')
--- 130000 tensor(0.0001, device='cuda:0')
--- 140000 tensor(0.0001, device='cuda:0')
--- 150000 tensor(0.0001, device='cuda:0')
--- 160000 tensor(0.0001, device='cuda:0')
--- 170000 tensor(9.7407e-05, device='cuda:0')
--- 180000 tensor(8.8266e-05, device='cuda:0')
--- 190000 tensor(8.0752e-05, device='cuda:0')
--- 200000 tensor(7.3767e-05, device='cuda:0')
--- 210000 tensor(6.7028e-05, device='cuda:0')
--- 220000 tensor(6.1289e-05, device='cuda:0')
-

(tensor([  89,   84,  185,  -12, -113,  -38,  -43,  193,  -67,  176],
        device='cuda:0', dtype=torch.int32),
 tensor([  89,   84,  185,  -12, -113,  -38,  -43,  193,  -67,  176],
        device='cuda:0', dtype=torch.int32),
 'acc',
 tensor(1., device='cuda:0'),
 'mae',
 tensor(0.0018, device='cuda:0'))

In [134]:
z1=x@w1 + b1
z1=z1.squeeze()

z2 = z1 @ w2 + b2
z2 = z2.squeeze()
acc = (z2.round().int() == y.int()).float().mean()
mae = (z2-y).abs().mean()
z2[:10].round().int(),y[:10].int(),'acc',acc,'mae',mae

(tensor([  89,   84,  185,  -12, -113,  -38,  -43,  193,  -67,  176],
        device='cuda:0', dtype=torch.int32),
 tensor([  89,   84,  185,  -12, -113,  -38,  -43,  193,  -67,  176],
        device='cuda:0', dtype=torch.int32),
 'acc',
 tensor(1., device='cuda:0'),
 'mae',
 tensor(0.0343, device='cuda:0'))

In [125]:

acc = (a2.round().int() == y.int()).float().mean()
mae = (a2-y).abs().mean()
loss = (a2-y).pow(2).mean()
a2[:10].int(),y[:10].int(),'acc',acc,'mae',mae,a2[:5],y[:5],a2[:5]-y[:5]
loss

tensor(33339.6562, device='cuda:0')

In [114]:
loss


tensor(0.0555, device='cuda:0')

In [137]:
w1,w2,b1,b2

(tensor([[-0.7461, -0.1930, -0.9312, -0.6244, -0.7052, -0.1128, -0.4714, -0.0189,
          -0.1588, -0.5772],
         [-0.3844, -0.3392, -0.2219, -0.1324, -0.6498, -0.3111, -0.4487, -0.1578,
          -0.9524, -0.5750],
         [-0.3716, -0.3072, -0.0829, -0.3593, -0.7935, -0.2286, -0.3399, -0.5763,
          -0.1856, -0.2675],
         [-0.1411, -0.3599, -0.5494, -0.4850, -0.4886, -0.5729, -0.5762, -0.7150,
          -0.2230, -0.8568],
         [-0.3387, -0.8364, -0.0457, -0.2867, -0.6966, -0.8386, -0.0061, -0.7016,
          -0.2149, -0.4239],
         [-0.0217, -0.4156, -0.9581, -0.1733, -0.1610, -0.3001, -0.5437, -0.7551,
          -0.5182, -0.5947],
         [-0.5053,  0.0902, -0.6820, -0.8513, -0.8712, -0.1698, -0.5218, -0.5694,
          -0.2277, -0.9707],
         [-0.5630, -0.7109, -0.9070, -0.7813, -0.2540, -0.3079, -0.0867, -0.7027,
          -0.4645, -0.1795],
         [-0.6115, -0.4992, -0.5287, -0.6309, -0.3650, -0.3525, -0.2978, -0.3643,
          -0.7676, -0.7221],
 